version: '3.8'

services:
    api_server:
        build: 
            context: .
            dockerfile: Dockerfile
        image: setara/api_server:release
        container_name: api_server
        env_file: prod.env
        networks: 
            - setaralms_network
        volumes: 
            - ./public:/usr/src/app/public
            - /etc/letsencrypt/archive/api.setara.kemdikbud.go.id/:/usr/src/app/ssl
        ports:
            - 8443:8443
        command: npm run start

networks: 
    setaralms_network:
        name: setaralms_network
