version: '3.8'

services:
    api_server:
        build: 
            context: .
            dockerfile: Dockerfile
        image: setara/api_server:release
        container_name: api_server
        env_file: dev.env
        networks: 
            - setaralms_network
        volumes: 
            - ./public:/usr/src/app/public
            - ./ssl:/usr/src/app/ssl
        ports:
            - 8000:8000
        command: npm run start

networks: 
    setaralms_network:
        name: setaralms_network